### ISSUE TITLE
Check if we need a new endpoint for the transaction details screen or just reuse the existing data (all-transactions)

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-ios#219]

**Comment by tschubotz** [comment]
Sprint planning discussion:
- There is no separate endpoint for this.
- Hence let's pass along the data/object from the "all-txs" endpoint.
- Getting the rejections would require currently querying another endpoint. Specifically figuring out rejections is hard since it is basically a confirmation of another txs. This other tx can be a cancellation or another propose (non-cancel) tx.

So:
- We show all transactions in the list, i.e. including the "0 ETH, no data" txs.
- Cancelled transactions do not display "rejections" but display who confirmed and display the "cancelled" status (Since there is another executed tx that cancelled this one)

@tschubotz put this info in the connected epic for future reference. also add examples
