### ISSUE TITLE
[iOS] transferFrom transaction is not displayed

### ISSUE THREAD

**Issue by sche** [gnosis/safe-ios#245]
**Bug description**
transferFrom transaction is not displayed in the transactions list

**Steps To Reproduce**
load safe 0xEefFcdEAB4AC6005E90566B08EAda3994A573C1E

**Comment by liliya-soroka** [comment]
Reopned:
the transaction TransferFrom nonce 7 is not displayed in the mobile app ( see the safe from steps to reproduce)

**Comment by DmitryBespalov** [comment]
Can you please double check, because I see this transaction - it is the first one in the list (nonce 7), it is an incoming transfer to the safe itself from some other account.

![IMG_6E1ADABB9709-1.jpeg](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/6df5f19a-ef97-4bcd-ae8e-45d1decce596)

**Comment by sche** [comment]
TODO: clarify requirements

**Comment by DmitryBespalov** [comment]
Backlog refinement: we keep it how it is - we keep the 1:1 transaction mapping from the server response.

**Comment by liliya-soroka** [comment]
the issue is verified and closed for the case when safe is a To .
For other cases the separate issues is created as in all cases the transferFrom is displayed as incoming tx
app version 0.5.0 (69)
